### ISSUE TITLE
Crash on latest a9lh

### ISSUE THREAD

**Issue by ghost** [xerpi/arm9linuxfw#1]
![linux error](https://cloud.githubusercontent.com/assets/18313411/21878323/408e0456-d870-11e6-9ab0-c6565b35b8d9.jpg)

**Comment by xerpi** [comment]
It looks like the Linux kernel wasn't correctly loaded, maybe it's a problem of https://github.com/xerpi/a9lh_linux_loader instead.

**Comment by ghost** [comment]
Same mistake. Also try compiling it on my part but the same thing happens to me.

**Comment by deathspawn** [comment]
I'm getting an error too. Using the build from gbatemp and the latest boot9strap. Screen looks like picture above. Also on n3ds 11.4.

**Comment by xerpi** [comment]
@deathspawn I guess you are using https://github.com/xerpi/firm_linux_loader, right?

**Comment by deathspawn** [comment]
@xerpi Yes. 1.2.

**Comment by profi200** [comment]
boot9strap dropped cakebrah framebuffers after 1.0 iirc so you would run into the same problem i had with our bootloader (crashes because of invalid framebuffer adresses).

**Comment by xerpi** [comment]
Switched to own libc implementation instead of using the one shipped with devkitARM.
